### ISSUE TITLE
Add link to Strava Heatmap

### ISSUE THREAD

**Issue by sylvain-m** [tankaru/OpenSwitchMapsWeb#1]
Hi,
I use your very useful plugin very regularly, and I take this opportunity to thank you for it.
I would like to suggest you to add a link to the Strava (global) heatmap.
The URLs seem quite simple to integrate, here an exemple : 
https://www.strava.com/heatmap#7.41/1.76427/44.40015/hot/all
If this is possible, I thank you in advance.
Sylvain M.

**Comment by tankaru** [comment]
Thanks a lot.
I added STRAVA map to the list.
