### ISSUE TITLE
Gribrouillon does not work

### ISSUE THREAD

**Issue by KovalevArtem** [tankaru/OpenSwitchMapsWeb#11]
![image](https://user-images.githubusercontent.com/36500228/120391747-2a49da00-c338-11eb-9050-8a10b2d6db83.png)
https://gribrouillon.fr/#4/0/0

**Comment by tankaru** [comment]
Thanks for your report.
I don't know if this is a temporary situation or if the service has been stopped.
I'll wait for a while.

**Comment by tankaru** [comment]
Gribrouillon seems fine.
