### ISSUE TITLE
Walking Town Map Maker does not work

### ISSUE THREAD

**Issue by KovalevArtem** [tankaru/OpenSwitchMapsWeb#13]
![image](https://user-images.githubusercontent.com/36500228/120393054-05566680-c33a-11eb-8d0d-feab1d97343d.png)
https://k-sakanoshita.github.io/mapmaker/#4/0/0

**Comment by tankaru** [comment]
Thanks for your report.
I've updated the link.
https://armd-02.github.io/mapmaker/#6/34.708/135.502
