### ISSUE TITLE
Wikimedia maps - Error

### ISSUE THREAD

**Issue by KovalevArtem** [tankaru/OpenSwitchMapsWeb#14]
![image](https://user-images.githubusercontent.com/36500228/120893318-4fca3280-c61b-11eb-9ded-a92456d0e72a.png)
https://maps.wikimedia.org/#4/0/0

**Comment by tankaru** [comment]
wikimedia maps is fine but it seems it doesn't accept jump from external site.
I need to copy and paste on URL bar.
Well, it's unfriendly, I'll remove wikipedia maps.
