### ISSUE TITLE
Can't correct transfer WGS84 location for Baidu map

### ISSUE THREAD

**Issue by LaoshuBaby** [tankaru/OpenSwitchMapsWeb#16]
You can try this:

<hr>

1. Find a point in OSM

```
https://www.openstreetmap.org/?mlat=39.9164&mlon=116.3911&zoom=16#map=16/39.9164/116.3911
```

![图片](https://user-images.githubusercontent.com/42690037/159115232-8227d6f5-46fd-4e65-8f7d-9df2b792266a.png)

2. Use OpenSwitchMaps in bookmark

The url is correct

```
https://tankaru.github.io/OpenSwitchMapsWeb/index.html#https://www.openstreetmap.org/?mlat=39.9164&mlon=116.3911&zoom=16#map=16/39.9164/116.3911
```
![图片](https://user-images.githubusercontent.com/42690037/159115261-a0ffe7e0-c94e-42bc-80d1-3fbe887ab394.png)

3. Jump to baidu map

OpenSwitchMap will jump me to ```http://map.baidu.com/?latlng=39.9164,116.3911```, then it will redirect to

```
https://map.baidu.com/@12956738.963192627,4826126.150428094,15.72z/latlng%3D39.9164%252C116.3911
```

![图片](https://user-images.githubusercontent.com/42690037/159115322-99e31db9-ef76-4863-bb08-a5db3fd60e93.png)

<hr>

At first I'm in forbidden city, but now I'm drowing in a lake.

This is because [中国における地理的データの制限#BD-09](https://ja.wikipedia.org/wiki/%E4%B8%AD%E5%9B%BD%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E5%9C%B0%E7%90%86%E7%9A%84%E3%83%87%E3%83%BC%E3%82%BF%E3%81%AE%E5%88%B6%E9%99%90#BD-09), and baidu map using this.

**Comment by tankaru** [comment]
Thank you for the information.
The Baidu map coordinate conversion is very very rough. Sorry.
Is there any coordinate conversion code in the link you sent? I could not find it.
https://github.com/caijun/geoChina returned 404.

**Comment by tankaru** [comment]
Sorry my reply was wrong.
I tried to implement the conversion of Baidu map coordinates, but the result was rough too much.
So I didn't implement it.
Now I will try again...

**Comment by tankaru** [comment]
@LaoshuBaby I've done it!
Could you try again?

**Comment by tankaru** [comment]
Maybe I've done it.
Could you try again?

**Comment by LaoshuBaby** [comment]
> Sorry my reply was wrong. I tried to implement the conversion of Baidu map coordinates, but the result was rough too much. So I didn't implement it. Now I will try again...

Sorry for late reply too, I also missed this comment and before.

It works correct now! Thank you for those work!
