### ISSUE TITLE
Add a text box to input url of the web map

### ISSUE THREAD

**Issue by GHolk** [tankaru/OpenSwitchMapsWeb#34]
Hey, I just find this online tool, which is great!

Currently, we have to use the bookmarklet or compose the url manually.
Can we add a `<input type="text">` text box to allow user input or paste url on webpage directly?
Maybe we can also make all links get updated without refresh the page.

If you like this feature, I can open a PR too.

**Comment by GHolk** [comment]
Other questions:
* Are you willing to add the `geo:` url link?
* Are you willing to add a pin after jump to the web map? Maybe only some web map support showwing a pin from url.
* When jump from google map, the coordinate is the center of the map, but not the pinned point. Can we change this?

**Comment by tankaru** [comment]
Hi
> Can we add a <input type="text"> text box
Do you mean if I put url string of Google maps, then converted urls such as Openstreetmap are produced?
That sounds reasonable for me.

**Comment by tankaru** [comment]
> Are you willing to add the geo: url link?

I’m not going at geo url link, how it is used.

**Comment by tankaru** [comment]
> Are you willing to add a pin after jump to the web map? Maybe only some web map support showwing a pin from url.
> When jump from google map, the coordinate is the center of the map, but not the pinned point. Can we change this?

I think it’s better to add pin when jumped from pinned map.
but It could be confusing if pinned point is out of screen.
 I cannot decide the best solution

**Comment by tankaru** [comment]
It’s sorry now I cannot use my dev pc for months, so I cannot write codes

**Comment by GHolk** [comment]
[Geo url in wikipedia](https://en.wikipedia.org/wiki/Geo_URI_scheme)
On android, a geo url will open the coordinate in the default map app, though mostly it will not work on desktop.
The [geohack](https://geohack.toolforge.org/geohack.php?language=en&pagename=&params=39.9142_N_116.3849_E_scale:6250_region:#regional) does offer a geo url link. (on right-top box)
The open street map offers the geo url in its share menu too.
One can send a location without a web map url with geo url.

However, only some apps make `geo:xxx` in messages clickable currently, so usually people can not send geo url directly.

**Comment by tankaru** [comment]
URL textbox is added to refresh map links.
And pinned map support is moved to a new issue.
https://github.com/tankaru/OpenSwitchMapsWeb/issues/35
