### ISSUE TITLE
Reduce unnecessary duplication of work in 2 “OSM”

### ISSUE THREAD

**Issue by LaoshuBaby** [tankaru/OpenSwitchMapsWeb#67]
I recently noticed that you have another plugin that uses a very similar datastore to this project, And every time a contributor makes changes in this project, you have to take extra time to synchronize the changes here: 
https://github.com/tankaru/OpenSwitchMaps/blob/master/src/maps.js

I have a suggestion, maybe we can extract this part of data separately as a npm package, and then refer to this package in both the Web switcher and the plugin switcher to reduce duplication of work (like [NSI](https://github.com/osmlab/name-suggestion-index) in OSM ecosystem?)

Is this possible? At the same time, this can also allow the data to be separated, which is more conducive to being used by potential users?

Thank you for reading my unrealistic expectations for this project (in #65 I also mentioned multilingual support and auto-formatting CI)

**Comment by LaoshuBaby** [comment]
By the way, is the acronym **O**pen**S**witch**M**ap confusing with **OSM**?

**Comment by tankaru** [comment]
The format of the map list is same. So I just copy and paste it. Not a hard work.

**Comment by tankaru** [comment]
And see https://github.com/tankaru/OpenSwitchMaps/issues/7
